### ISSUE TITLE
bruh

### ISSUE THREAD

**Issue by TheAwesome98-Real** [pspdev/pspdev#1]
i386 support pls

```sh
user@computer: ~/Desktop/stuff/playstation/psp/homebrew/Minecraft $ psp-gcc main.c
bash: /bin/psp-gcc: cannot execute binary file: Exec format error
```

**Comment by carstene1ns** [comment]
Added support in: https://github.com/pspdev/pspdev/tree/ubuntu-x86

Please try out the following archive an tell me if it works:
https://github.com/pspdev/pspdev/suites/934038959/artifacts/11506971

**Comment by TheAwesome98-Real** [comment]
Okay, i will try, thanks

**Comment by TheAwesome98-Real** [comment]
I tested and it worked

**Comment by carstene1ns** [comment]
Fixed with v20200725-2.
