### ISSUE TITLE
Docker | `linux/arm64/v8` host platform

### ISSUE THREAD

**Issue by sjsone** [pspdev/pspdev#14]
I tried using the provided docker-image on a Macbook M1 but got the following error: 

```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/bin/bash": stat /bin/bash: no such file or directory: unknown.
```

This is the command to test it `docker run --rm -it pspdev/pspdev:latest /bin/bash`

Would it be possible to provide a suitable cross-compiled image via the github actions ?

**Comment by sajattack** [comment]
I'll consider working on this after I get riscv64gc working.

**Comment by sajattack** [comment]
https://github.com/pspdev/pspdev/releases/tag/v20220202

**Comment by sajattack** [comment]
Unfortunately the build job to do this runs for like 3 hours each architecture... So it might not make sense to merge it to the main CI pipeline.

**Comment by fjtrujy** [comment]
Hello @sjsone you can install natively in Macos M1/M2... already, so please download from releases or install it yourself.

Please, let us know if works for you

**Comment by sjsone** [comment]
hi @fjtrujy thanks for getting back!

Well, running it in a container and installing it locally might not be the same use case. 
I wanted to install it on my compiling cluster so i do not have to install it locally :D

With the help of the Dockerfile and the Readme i just built the images myself. I initially thought that providing builds for ARM is not as heavy on the pipeline as @sajattack since then found out. 

So i think this issue can be closed as https://github.com/pspdev/pspdev/labels/wontfix for now

**Comment by sajattack** [comment]
also fyi I recently made an alpine arm64 pspdev release, just mount this folder into an alpine 3.16 container and you should be set https://github.com/pspdev/pspdev/releases/download/v20220202/pspdev-alpine-aarch64-20240520.tar.gz
