### ISSUE TITLE
！

### ISSUE THREAD

**Issue by Toy-Gun** [pspdev/pspdev#18]
因为热爱，所以坚持

**Comment by sharkwouter** [comment]
This seems to be spam. I threw it in Google translate and I'm just more confused.

**Comment by Toy-Gun** [comment]
hahaha
I just want to express my gratitude to you
I'll delete it





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Wouter ***@***.***&gt;; 
发送时间: 2022年2月5日(星期六) 凌晨1:16
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [pspdev/pspdev] ！ (Issue #18)





 
This seems to be spam. I threw it in Google translate and I'm just more confused.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Toy-Gun** [comment]
I’m sorry to have caused you trouble.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Wouter ***@***.***&gt;; 
发送时间: 2022年2月5日(星期六) 凌晨1:16
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [pspdev/pspdev] ！ (Issue #18)





 
Closed #18.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
