### ISSUE TITLE
`pspdev/pspdev` Docker image might be incomplete

### ISSUE THREAD

**Issue by filfreire** [pspdev/pspdev#19]
> TL;DR: I think the Docker image that is being pushed to [Docker Hub](https://hub.docker.com/r/pspdev/pspdev/tags) and [Github image repo](https://github.com/pspdev/pspdev/pkgs/container/pspdev) might be missing `build-all.sh` (or equivalent) steps in order to be readily mounted and used to compile projects

If we try to use `pspdev/pspdev`  or `ghcr.io/pspdev/pspdev` to make a project, e.g. running a command like:

```shell
 docker run -v "`pwd`:/build" --rm -it pspdev/pspdev  make
```

We will get an error like:
```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "make": executable file not found in $PATH: unknown.
```

Same happens if we use `ghcr.io/pspdev/pspdev`.

If I try to run `apk add make` inside the container, and then run `make`, I start getting other errors with missing files:
```
Error loading shared library libmpc.so.3: No such file or directory (needed by /usr/local/pspdev/libexec/gcc/psp/11.2.0/cc1plus)
Error loading shared library libmpfr.so.6: No such file or directory (needed by /usr/local/pspdev/libexec/gcc/psp/11.2.0/cc1plus)
Error loading shared library libgmp.so.10: No such file or directory (needed by /usr/local/pspdev/libexec/gcc/psp/11.2.0/cc1plus)
Error relocating /usr/local/pspdev/libexec/gcc/psp/11.2.0/cc1plus: mpfr_hypot: symbol not found
Error relocating /usr/local/pspdev/libexec/gcc/psp/11.2.0/cc1plus: __gmpz_cmp: symbol not found
Error relocating /usr/local/pspdev/libexec/gcc/psp/11.2.0/cc1plus: mpfr_set_emin: symbol not found
```

## Notes 

I first noticed this issue while using the (now archived) [pspdev-docker](https://github.com/pspdev/pspdev-docker), where I had to point to `pspdev` instead of `psptoolchain` (see [this PR](https://github.com/pspdev/pspdev-docker/pull/15)).

The build using the [Dockerfile](https://github.com/filfreire/pspdev-docker/blob/main/Dockerfile) where we call `build-all.sh` has a huge difference in size to the official public images, which, despite being on a different base image (e.g. `alpine` vs `ubuntu`), I suspect, taking into account the errors above,  could be due to the `pspdev/pspdev` images missing also files.
```
$docker images
REPOSITORY                        TAG       IMAGE ID       CREATED        SIZE
ghcr.io/filfreire/pspdev-docker   latest    21cb99b89fe3   38 hours ago   984MB
pspdev/pspdev                     latest    6faeed61bddf   6 days ago     240MB
ghcr.io/pspdev/pspdev             latest    6faeed61bddf   6 days ago     240MB
```

I see that in [the actions](https://github.com/pspdev/pspdev/blob/master/.github/workflows/compilation.yml#L125), the `build-all.sh` is run for `ubuntu:latest` BUT, it is not run for the [base Dockerfile](https://github.com/pspdev/pspdev/blob/master/Dockerfile), so I was wondering if this is on purpose - e.g. the provided container is not meant to have the pre-baked/compiled toolchain?

**Comment by fjtrujy** [comment]
The docker image is super tiny doesn't all the dependencies that you may need ínstales, it is like the "alpine:latest" but with all the psp ready.

Just do:
```
apk add build-base bash
```
Or you other missing requirements.
