### ISSUE TITLE
Cannot compile on MacOS Catalina 

### ISSUE THREAD

**Issue by UNSTOP4BLE** [pspdev/pspdev#34]
the prebuilts dont work so i tried to compile it from source but i get these errors 
../../../libgcc/config/hardfp.c:61:2: error: #error Unknown operation
   61 | #error Unknown operation
      |  ^~~
make[2]:  [addsf3.o] Error 1
make[2]:  Waiting for unfinished jobs....
../../../libgcc/config/hardfp.c:61:2: error: #error Unknown operation
   61 | #error Unknown operation
      |  ^
../../../libgcc/config/hardfp.c:61:2: error: #error Unknown operation
   61 | #error Unknown operation
      |  ^
make[2]:  [negsf2.o] Error 1
make[2]:  [subsf3.o] Error 1
../../../libgcc/config/hardfp.c:61:2: error: #error Unknown operation
   61 | #error Unknown operation
      |  ^~~
make[2]:  [mulsf3.o] Error 1
make[1]:  [all-target-libgcc] Error 2
make: *** [all] Error 2

**Comment by sharkwouter** [comment]
Did you figure it out?

**Comment by UNSTOP4BLE** [comment]
i didnt see there was a mac fix branch with releases
