### ISSUE TITLE
 build-all.sh fails to install on macOS Ventura 13.0 (22A380)

### ISSUE THREAD

**Issue by dogo** [pspdev/pspdev#37]
```
➜  pspdev git:(master) sh build-all.sh 
Installing latest environment status
HEAD is now at f63dad3 Merge pull request #162 from z2442/patch-1
Installing latest environment status
Using repo reference main
HEAD is now at 19a924c Merge pull request #10 from pspdev/gdb-without-python-on-ci-build
Already on 'main'
Your branch is up to date with 'origin/main'.
Installing latest environment status
fatal: ambiguous argument 'origin/allegrex-v2.37.0': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
../scripts/001-binutils.sh: Failed.
../scripts/001-allegrex.sh: Failed.
../scripts/001-psptoolchain.sh: Failed.
```

**Comment by wally4000** [comment]
Apple Silicon requires some work, including GCC 12 to work, this issue will be corrected when this comes into scope.

I'd suggest using this autobuild https://github.com/pspdev/pspdev/releases/download/latest/pspdev-macos-latest.tar.gz which does work on Intel Macs (and if you do a bit of messing around with homebrew it will work on Apple Silicon too)e

Note you'll need to manually add each binary to gatekeeper (This is a script i'll add a bit later for macOS which is on the todo list
