### ISSUE TITLE
Docker missing cmake package

### ISSUE THREAD

**Issue by SeleDreams** [pspdev/pspdev#40]
Hi, I'm posting this issue to notify that the docker image of pspdev lacks the cmake package. It is necessary for the psp-cmake command that is bundled in the toolchain, without it, the psp-cmake command fails

```
seledreams@seledreams-Predator-PH315-51:~$ docker run --rm -it pspdev/pspdev:latest
/ # psp-cmake /usr/local/pspdev/bin/psp-cmake: line 10: cmake: command not found
```

it's easy to fix by using apk add cmake in a dockerfile using the image, but it would be more convenient if it was already bundled in the image. cmake shouldn't be that heavy of a package to include

**Comment by wally4000** [comment]
Hi SeleDreams,

This has now been resolved, please try again in about an hour :)
