### ISSUE TITLE
pspdev.cmake sets system name as Generic

### ISSUE THREAD

**Issue by SeleDreams** [pspdev/pspdev#41]
Hi,
I was wondering if it would be possible to set the system name of the PSP in the cmake to an actual name like SonyPSP or PSP ? because when setting up cmake systems alongside devkitpro toolkits, it ends up looking pretty dirty to have to suddenly change the type of platform check 

It's far from an emergency since it works as intended, but I feel like it is probably better to set an accurate system name rather than keeping it as "generic"

![image](https://user-images.githubusercontent.com/16335601/215860755-6d585c9b-de2c-41c7-b93d-abfe980db577.png)

**Comment by sharkwouter** [comment]
That's a good idea, I'll make a merge request for it.
