### ISSUE TITLE
Debian removed gpgme-config binary, fix script accordingly.

### ISSUE THREAD

**Issue by ParzivalWolfram** [pspdev/pspdev#44]
Per Debian bug tracker at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1023601, the `gpgme-config` binary is no longer included in favor of `gpgrt-config`. Message 20 in the bug report thread includes a possible workaround.

**Comment by asiekierka** [comment]
Arch Linux has done the same as of recently.

**Comment by wally4000** [comment]
We are pulling the base dev packages and not individual stuff, some further clarity (or pull requests) about where your areas of concern are would be fantastic.

**Comment by wally4000** [comment]
Hello,

I've done some further reviewing and understand that this might impact some building.
I'll look into this further

Thanks for reporting

**Comment by wally4000** [comment]
Patch has been applied.
