### ISSUE TITLE
windows10 msys2 build problem

### ISSUE THREAD

**Issue by leecloudvictor** [pspdev/pspdev#45]
make[2]: Entering directory '/d/dev/Scoop/persist/msys2/home/leecl/pspsdk/pspdev/build/psptoolchain/build/psptoolchain-allegrex/build/gcc/build-psp-stage2/psp/libstdc++-v3/include'
echo timestamp > stamp-pb
echo timestamp > stamp-host
make[2]: [Makefile:1767: psp/bits/largefile-config.h] Error 1 (ignored)
make[2]: [Makefile:1768: psp/bits/largefile-config.h] Error 1 (ignored)
echo 0 > stamp-namespace-version
echo 1 > stamp-visibility
echo 1 > stamp-extern-template
echo 1 > stamp-dual-abi
echo 1 > stamp-cxx11-abi
echo 1 > stamp-allocator-new
echo 'undef _GLIBCXX_USE_FLOAT128' > stamp-float128
sed -e '/^#pragma/b' \
    -e '/^#/s/\([ABCDEFGHIJKLMNOPQRSTUVWXYZ_][ABCDEFGHIJKLMNOPQRSTUVWXYZ_]*\)/_GLIBCXX_\1/g' \
    -e 's/_GLIBCXX_SUPPORTS_WEAK/__GXX_WEAK__/g' \
    -e 's/_GLIBCXX___MINGW32_GLIBCXX___/__MINGW32__/g' \
    -e 's,^#include "\(.*\)",#include <bits/\1>,g' \
    < /home/leecl/pspsdk/pspdev/build/psptoolchain/build/psptoolchain-allegrex/build/gcc/libstdc++-v3/../libgcc/gthr.h > psp/bits/gthr.h
sed -e 's/\(UNUSED\)/_GLIBCXX_\1/g' \
    -e 's/\(GCC[ABCDEFGHIJKLMNOPQRSTUVWXYZ_]*_H\)/_GLIBCXX_\1/g' \
    < /home/leecl/pspsdk/pspdev/build/psptoolchain/build/psptoolchain-allegrex/build/gcc/libstdc++-v3/../libgcc/gthr-single.h > psp/bits/gthr-single.h
sed -e 's/\(UNUSED\)/_GLIBCXX_\1/g' \
    -e 's/\(GCC[ABCDEFGHIJKLMNOPQRSTUVWXYZ_]*_H\)/_GLIBCXX_\1/g' \
    -e 's/SUPPORTS_WEAK/__GXX_WEAK__/g' \
    -e 's/\([ABCDEFGHIJKLMNOPQRSTUVWXYZ_]*USE_WEAK\)/_GLIBCXX_\1/g' \
    < /home/leecl/pspsdk/pspdev/build/psptoolchain/build/psptoolchain-allegrex/build/gcc/libstdc++-v3/../libgcc/gthr-posix.h > psp/bits/gthr-posix.h
sed -e 's/\(UNUSED\)/_GLIBCXX_\1/g' \
    -e 's/\(GCC[ABCDEFGHIJKLMNOPQRSTUVWXYZ_]*_H\)/_GLIBCXX_\1/g' \
    -e 's/SUPPORTS_WEAK/__GXX_WEAK__/g' \
    -e 's/\([ABCDEFGHIJKLMNOPQRSTUVWXYZ_]*USE_WEAK\)/_GLIBCXX_\1/g' \
    -e 's,^#include "\(.*\)",#include <bits/\1>,g' \
    < /home/leecl/pspsdk/pspdev/build/psptoolchain/build/psptoolchain-allegrex/build/gcc/libstdc++-v3/../libgcc/gthr-posix.h > psp/bits/gthr-default.h
make[2]: Leaving directory '/d/dev/Scoop/persist/msys2/home/leecl/pspsdk/pspdev/build/psptoolchain/build/psptoolchain-allegrex/build/gcc/build-psp-stage2/psp/libstdc++-v3/include'
Making all in include
In file included from /home/leecl/pspsdk/pspdev/build/psptoolchain/build/psptoolchain-allegrex/build/gcc/build-psp-stage2/psp/libstdc++-v3/include/unordered_set:47,
                 from /home/leecl/pspsdk/pspdev/build/psptoolchain/build/psptoolchain-allegrex/build/gcc/libstdc++-v3/include/precompiled/stdc++.h:118:
/home/leecl/pspsdk/pspdev/build/psptoolchain/build/psptoolchain-allegrex/build/gcc/build-psp-stage2/psp/libstdc++-v3/include/bits/unordered_set.h:1882:1: internal compiler error: Segmentation fault
 1882 | } // namespace std
      | ^
0x100a90f79 crash_signal
        ../../gcc/toplev.c:327
0x10084773f ???
        /home/leecl/pspsdk/pspdev/build/psptoolchain/build/psptoolchain-allegrex/build/gcc/build-psp-stage2/gcc/gtype-desc.c:7471
0x1007f645e gt_pch_save(__sFILE64*)
        ../../gcc/ggc-common.c:549
0x10062a997 c_common_write_pch()
        ../../gcc/c-family/c-pch.c:177
0x10048fa8c c_parse_final_cleanups()
        ../../gcc/cp/decl2.c:4909
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <https://gcc.gnu.org/bugs/> for instructions.
make[4]: *** [Makefile:1862: psp/bits/stdc++.h.gch/O2ggnu++0x.gch] Error 1
make[4]: *** Waiting for unfinished jobs....
In file included from /home/leecl/pspsdk/pspdev/build/psptoolchain/build/psptoolchain-allegrex/build/gcc/libstdc++-v3/include/precompiled/stdc++.h:133:
/home/leecl/pspsdk/pspdev/build/psptoolchain/build/psptoolchain-allegrex/build/gcc/build-psp-stage2/psp/libstdc++-v3/include/variant:1848:1: internal compiler error: Segmentation fault
 1848 | } // namespace std
      | ^
0x100a90f79 crash_signal
        ../../gcc/toplev.c:327
0x10084773f ???
        /home/leecl/pspsdk/pspdev/build/psptoolchain/build/psptoolchain-allegrex/build/gcc/build-psp-stage2/gcc/gtype-desc.c:7471
0x1007f645e gt_pch_save(__sFILE64*)
        ../../gcc/ggc-common.c:549
0x10062a997 c_common_write_pch()
        ../../gcc/c-family/c-pch.c:177
0x10048fa8c c_parse_final_cleanups()
        ../../gcc/cp/decl2.c:4909
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <https://gcc.gnu.org/bugs/> for instructions.
make[4]: *** [Makefile:1867: psp/bits/stdc++.h.gch/O2g.gch] Error 1
make[3]: *** [Makefile:568: all-recursive] Error 1
make[2]: *** [Makefile:493: all] Error 2
make[1]: *** [Makefile:12145: all-target-libstdc++-v3] Error 2
make: *** [Makefile:957: all] Error 2
../scripts/005-gcc-stage2.sh: Failed.
../scripts/001-allegrex.sh: Failed.
../scripts/001-psptoolchain.sh: Failed.

**Comment by sharkwouter** [comment]
So, we used to have incomplete msys2 builds, but we decided against continuing support for it as using the Ubuntu version in wsl works very well.

Take a look at https://pspdev.github.io/ for instructions. Hope that helps.
