### ISSUE TITLE
[Question] Would you be interested in adding Cygwin scripts and patches?

### ISSUE THREAD

**Issue by xan1242** [pspdev/pspdev#49]
Hello,

For the past 2 days I had the absolute pleasure (read: nightmare) of building the toolchain under cygwin.

My question is mainly this - would you be interested adding in some extra patches (that I could write) for this toolchain to build and work under cygwin?

I know Docker and WSL are available, but this would still benefit Windows dev setups in a few ways:

- No need for virtualization setup
- More portable deployment for Windows developers - you can pack the cygwin environment in a folder basically and ship it out
- Because it's so portable, it's easier to integrate into existing Visual Studio projects that center around Windows (real example of this is [Widescreen Fixes Pack](https://github.com/ThirteenAG/WidescreenFixesPack))

There are a few cons though:

- cygwin has some key libraries that are unmaintained (python is at 3.9, libgpgme doesn't even have `GPGME_KEYLIST_MODE_LOCATE`, etc.)
- it's still Windows speaking the POSIX language, so it's janky by nature
- gcc stage 2 building can randomly segfault during its build process
- cygwin seems to have slowed its development down, especially with WSL and compared to MSYS2

(for MSYS2 if you were wondering I did try it and it fails to compile gdb and gcc, complaining about missing config.h in libiberty)

Still, considering the pace of the project, I think it's still a somewhat viable option, but that's why I'm asking you first before I do anything.

## What had to be done to get it working

As for a quick summary what needs to be done to get it working (this is not yet comprehensive, just from notes I have):

- in addition to the requirements in the README, the following packages (and all of their `-devel` packages, including for the ones in README) need to be installed too: `automake`, `autoconf`, `libarchive`, `libncurses-devel`, `openssl-devel`, `python3-virtualenv`, `python3.9-pip`, `python3.9`
- `libiconv` currently does not ship with a pkgconfig and one has to be created manually in `/lib/pkgconfig/iconv.pc` , example:
```
prefix=/usr
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

Name: iconv
Description: Character set conversion library
Version: 1.17-1
Libs: -L${libdir} -liconv
Cflags: -I${includedir}
```
(replace the version with one you have)
- `libgpgme` is currently at version 1.9, which is before the implementation of the `GPGME_KEYLIST_MODE_LOCATE` flag, so it has to be replaced with `GPGME_KEYLIST_MODE_LOCAL | GPGME_KEYLIST_MODE_EXTERN`  in pacman/libalpm source `lib/libalpm/signing.c`
- meson.build installation fails (for pacman 6.0.1) because at line 409 the slash has to be removed from $DESTDIR:

from:
```
meson.add_install_script('sh', '-c', 'mkdir -p "$DESTDIR/@0@"'.format(path))
```
to:
```
meson.add_install_script('sh', '-c', 'mkdir -p "$DESTDIR@0@"'.format(path))
```

- and last, but not least, you need to enable wget as the XferCommand in `pacman.conf` by uncommenting its line: `XferCommand = /usr/bin/wget --passive-ftp -c -O %o %u`

And that basically wraps up the needed changes for cygwin to compile this toolchain. It's very messy as you can see, but I think it could be done. I hadn't checked extras much (the psplink stuff) so I'm not even sure if that would compile...

**Comment by sharkwouter** [comment]
We had msys2 builds for a while, but it wasn't working well and the builds were a nightmare to maintain. Because of this we switched to recommending people to use WSL and discontinued the Windows builds.

If someone is willing to maintain Windows builds, then perhaps it could be interesting to have, but right now we don't have anyone. We also don't want randomly failing builds. Theoretically it's all possible, in reality it's quite the maintenance burden.

**Comment by sharkwouter** [comment]
That is actually the problem, each time we update binutils or gcc the build will fail. We have done this a couple of times in the last 2 years.

**Comment by xan1242** [comment]
Ah I see then. That would explain the issues in MSYS2 I had with building gdb. (Although from what I've read this is because of the new glibc trying to compile old code, not the other way around)

Alrighty then. Considering there's only one project in need of a Windows build, I'd say this is too niche to maintain.

Then perhaps a short guide somewhere (in the wiki for example) will suffice. With the notes I posted earlier, anyone who needs the SDK in Windows specifically shouldn't have as hard of a time I had.

If you want me to write it up, let me know and I'll come up with something.

**Comment by tpimh** [comment]
@xan1242 Did you post your Windows compilation instructions somewhere in the Wiki?
