### ISSUE TITLE
Support /opt/homebrew/bin/brew homebrew patth

### ISSUE THREAD

**Issue by JamaicaNater** [pspdev/pspdev#62]
I've encountered an issue with the setup script that currently checks for Homebrew only in its default installation path for Intel Macs (`/usr/local/bin/brew`). As Apple Silicon Macs use a different default path (`/opt/homebrew/bin/brew`), the script fails to recognize Homebrew installations on these newer machines.

**Comment by sharkwouter** [comment]
Thanks for fixing this!
