### ISSUE TITLE
Build Deps: Mac Ports? Do we really need it here?

### ISSUE THREAD

**Issue by wally4000** [pspdev/pspdev#68]
As far as i'm aware Mac Ports isn't being used by Maintainers and CI/CD is electively using homebrew as it's tried and tested.

GIven we have nobody actively testing or updating deps for macports I would suggest we remove it from the prepare script.

**Comment by sharkwouter** [comment]
I think we initially set up Mac Ports in the script because something was missing in Brew. Feel free to update the script now.

**Comment by wally4000** [comment]
Closing this off as macports still somewhere deeply integrated
